## Logistic Regression Model

In [11]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from PIL import Image
import os

# Define the emotions and their corresponding labels
emotions = {
    'angry': 0,
    'disgust': 1,
    'fear': 2,
    'happy': 3,
    'neutral': 4,
    'sad': 5,
    'surprise': 6
}

# Define the paths to the training and validation directories
train_dir = '../datasets/train/'
val_dir = '../datasets/validation/'

# Define the image size
img_size = (48, 48)

# Load the training data
X_train = []
y_train = []
for emotion, label in emotions.items():
    for filename in os.listdir(train_dir + emotion):
        img = Image.open(train_dir + emotion + '/' + filename)
        img = img.resize(img_size)
        X_train.append(np.array(img).flatten())
        y_train.append(label)

X_train = np.array(X_train)
y_train = np.array(y_train)

# Load the validation data
X_val = []
y_val = []
for emotion, label in emotions.items():
    for filename in os.listdir(val_dir + emotion):
        img = Image.open(val_dir + emotion + '/' + filename)
        img = img.resize(img_size)
        X_val.append(np.array(img).flatten())
        y_val.append(label)

X_val = np.array(X_val)
y_val = np.array(y_val)

# Create a logistic regression model
model = LogisticRegression(max_iter=1000, multi_class='multinomial')

# Train the model on the training data
model.fit(X_train, y_train)

# Use the trained model to make predictions on the validation data
y_pred = model.predict(X_val)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_val, y_pred)
print('Accuracy:', accuracy)

# Calculate the confusion matrix of the model
cm = confusion_matrix(y_val, y_pred)
print('Confusion matrix:')
print(cm)

# Calculate the classification report of the model
cr = classification_report(y_val, y_pred, target_names=emotions.keys())
print('Classification report:')
print(cr)


Accuracy: 0.31870931219926407
Confusion matrix:
[[154  36 121 262 130 164  93]
 [ 16  25  11  20  16  13  10]
 [119  31 192 227 151 163 135]
 [157  35 148 964 210 212  99]
 [113  32 111 284 353 198 125]
 [142  45 131 269 194 242 116]
 [ 65  16  88 123  94  89 322]]
Classification report:
              precision    recall  f1-score   support

       angry       0.20      0.16      0.18       960
     disgust       0.11      0.23      0.15       111
        fear       0.24      0.19      0.21      1018
       happy       0.45      0.53      0.49      1825
     neutral       0.31      0.29      0.30      1216
         sad       0.22      0.21      0.22      1139
    surprise       0.36      0.40      0.38       797

    accuracy                           0.32      7066
   macro avg       0.27      0.29      0.27      7066
weighted avg       0.31      0.32      0.31      7066



c:\Users\65818\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
